ktor {
  deployment {
    port = 8083
    port = ${?PORT}
  }
  application {
    modules = [com.example.ApplicationKt.module]
  }
}
jwt {
  domain = "https://jwt-provider-domain/"
  audience = "jwt-audience"
  realm = "ktor sample app"
  secret = "your-super-secret-key-must-be-at-least-256-bits-long-for-hs512-algorithm"
  expiration = 86400
  issuer = "med-collab-system"
}
database {
  mysql {
    url = "jdbc:mysql://localhost:4000/metric?useSSL=false"
    user = "Hyy"
    password = "hyy20060420"
    driver = "com.mysql.cj.jdbc.Driver"
  }
}
koog{
  deepseek{
    apikey=${DEEPSEEK_API_KEY}
    baseUrl="https://api.deepseek.com"
  }
}
