ktor {
  deployment {
    port = 8084
    port = ${?PORT}
  }
  application {
    modules = [com.example.medcollab.report.ApplicationKt.module]
  }
}
database {
  mysql {
    url = "jdbc:mysql://mysql:3306/ktor_database?useSSL=false"
    user = "root"
    password = "password"
    driver = "com.mysql.cj.jdbc.Driver"
  }
}
