FROM eclipse-temurin:21-jdk AS builder
WORKDIR /build
COPY . .
COPY docker/gradle-dists /root/.gradle/wrapper/dists
RUN ./gradlew :api-gateway:installDist -x test --no-daemon -q

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/api-gateway/build/install/api-gateway/ .
EXPOSE 8088
ENTRYPOINT ["bin/api-gateway"]
