FROM node:22-alpine AS builder
WORKDIR /app
COPY frontend/ .

ENV VITE_GATEWAY_PORT=80
ENV VITE_METRIC_API_PORT=80
ENV VITE_AUTH_WS_PORT=80
ENV VITE_METRIC_WS_PORT=80

RUN npm ci --no-audit --no-fund && npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
