FROM eclipse-temurin:21-jdk AS builder
WORKDIR /build
COPY . .
RUN ./gradlew :metric-service:installDist -x test --no-daemon -q

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/metric-service/build/install/metric-service/ .
EXPOSE 8083
ENTRYPOINT ["bin/metric-service"]
