FROM eclipse-temurin:21-jdk AS builder
WORKDIR /build
COPY . .
COPY docker/gradle-dists /root/.gradle/wrapper/dists
RUN ./gradlew :patient-service:installDist -x test --no-daemon -q

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /build/patient-service/build/install/patient-service/ .
EXPOSE 8082
ENTRYPOINT ["bin/patient-service"]
