ktor {
  deployment {
    port = 8082
    port = ${?PORT}
  }
  application {
    modules = [com.example.ApplicationKt.module]
  }
}
jwt {
  domain = "https://jwt-provider-domain/"
  audience = "jwt-audience"
  realm = "ktor sample app"
  secret = "your-super-secret-key-must-be-at-least-256-bits-long-for-hs512-algorithm"
  expiration = 86400
  issuer = "med-collab-system"
}
database {
  mysql {
    url = "jdbc:mysql://localhost:4000/patient?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useInformationSchema=false&useUnicode=true&characterEncoding=UTF-8&nullDatabaseMeansCurrent=true"
    user = "Hyy"
    password = "hyy20060420"
    driver = "com.mysql.cj.jdbc.Driver"
  }
}
