ktor {
  deployment {
    port = 8082
    port = ${?PORT}
  }
  application {
    modules = [com.example.medcollab.patient.ApplicationKt.module]
  }
}
jwt {
  domain = "https://jwt-provider-domain/"
  audience = "jwt-audience"
  realm = "ktor sample app"
}
database {
  mysql {
    url = "jdbc:mysql://mysql:3306/ktor_database?useSSL=false"
    user = "root"
    password = "password"
    driver = "com.mysql.cj.jdbc.Driver"
  }
}
